apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whale-tracker-ingress
  namespace: whale-tracker-prod
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whale-backend
                port:
                  number: 8080