apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whale-tracker-prod

resources:
  - postgres-pvc.yaml
  - databases.yaml
  - rabbitmq.yaml
  - keycloak.yaml
  - backend.yaml
  - web.yaml
  - infra-services.yaml
  - strip-api-prefix.yaml
  - ingress.yaml

configMapGenerator:
  - name: domain-config
    envs:
      - ./env-context/.env
  - name: keycloak-realm-import
    files:
      - realm-export.json=./env-context/realm-export.json

replacements:
  - source:
      kind: ConfigMap
      name: domain-config
      fieldPath: data.HOSTNAME
    targets:
      - select:
          kind: Ingress
          name: whale-tracker-ingress
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0