server:
  port: 8080
  environment: "development"
  log_path: "/var/log/tracker/app.log"

authorization:
  issuer_url: "http://localhost:9090/realms/whale-tracker"
  client_id: "whale-tracker-app"

database:
  host: "localhost"
  port: 5432
  user: "tracker_admin"
  password: "super_secure_password"
  name: "whale_tracker"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

alchemy:
  api_key: ""

coingecko:
   api_key: ""

blockchain:
  ethereum_mainnet_rpc: "https://eth.drpc.org"
  ethereum_arbitrum_rpc: "https://arb1.arbitrum.io/rpc"
  ethereum_base_rpc: "https://rpc.baseazul.dev"
  polygon_mainnet: "https://polygon.gateway.tenderly.co"
  bnb: "https://bsc-mainnet.public.blastapi.io"
  solana_rpc: "https://api.mainnet-beta.solana.com"
  tron_grpc: "grpc.trongrid.io:50051"
  tron_api_key: "38bcc631-6749-4afb-9626-45afafd2af13"
  bitcoin:
    host: "localhost:8332"
    user: "admin"
    pass: "secretpassword"

token_registry:
  assets:
    - id: "btc-native"
      name: "Bitcoin"
      symbol: "BTC"
      items:
        - chain: "BTC"
          address: native
          decimals: 18
          is_native: true

    - id: "eth-native"
      name: "Ethereum"
      symbol: "ETH"
      items:
        - chain: "ETH"
          address: native
          decimals: 18
          is_native: true

    - id: "arbitrum"
      name: "Arbitrum"
      symbol: "ARB"
      items:
        - chain: "ARB"
          address: "native"
          decimals: 18
          is_native: true

    - id: "sol"
      name: "SOL"
      symbol: "SOL"
      items:
        - chain: "SOL"
          address: "native"
          decimals: 18
          is_native: true

    - id: "tron"
      symbol: "TRX"
      name: "Tron"
      items:
        - chain: "TRX"
          address: "native"
          decimals: 18
          is_native: true

    - id: "pol_polygon"
      symbol: "POL"
      name: "Polygon"
      items:
        - chain: "POL"
          address: "native"
          decimals: 18
          is_native: true

    - id: "tether-gold"
      name: "Tether Gold"
      symbol: "XAUt"
      items:
        - chain: "ETH"
          symbol: "XAUt"
          address: "0x68749665FF8D2d112Fa859AA293F07A622782F38"
          decimals: 6
          is_native: false
        - chain: "SOL"
          symbol: "XAUt0"
          address: "AymATz4TCL9sWNEEV9Kvyz45CHVhDZ6kUgjTJPzLpU9P"
          decimals: 18
          is_native: false
      
    - id: "paxg"
      symbol: "PAXG"
      name: "Paxos Gold"
      items:
        - chain: "ETH"
          address: "0x45804880De22913dAFE09f4980848ECE6EcbAf78"
          decimals: 18
          is_native: false

    - id: "usdc"
      name: "USDC"
      symbol: "USDC"
      items:
        - chain: "ETH" 
          address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
          decimals: 6
          is_native: false          
        - chain: "POL"
          address: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"
          decimals: 6
          is_native: false

    - id: "usdt"
      name: "Tether USD"
      symbol: "USDT"
      items: 
        - chain: "TRX"
          address: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
          decimals: 6
          is_native: false
        - chain: "ETH"
          address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
          decimals: 6
          is_native: false

    - id: "wbtc_ethereum"
      name: "Wrapped Bitcoin"
      symbol: "WBTC"
      items:
        - chain: "ETH"
          address: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
          decimals: 8
          is_native: false

    - id: "aaplx"
      symbol: "AAPLx"
      name: "Apple xStock"
      items:
        - chain: "ETH"
          address: "0xE5f6d3b2405ABdfE6F660e63202B25D23763160d"
          decimals: 18
          is_native: false
        - chain: "ARB"
          address: "0xE5f6d3b2405ABdfE6F660e63202B25D23763160d"
          decimals: 18
          is_native: false
        - chain: "SOL"
          address: "XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp"
          decimals: 18
          is_native: false

    - id: "gldx"
      symbol: "GLDx"
      name: "Gold xStock"
      items:
        - chain: "ETH"
          address: "0x2380F2673C640fB67E2d6B55B44C62F0E0e69DA9"
          decimals: 18
          is_native: false

    - id: "googlx"
      name: "Alphabet xStock"
      symbol: "GOOGLx"
      items:
        - chain: "ARB"
          address: "0xe92f673Ca36C5E2Efd2DE7628f815f84807e803F"
          decimals: 18
          is_native: false
        - chain: "SOL"
          address: "XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN"
          decimals: 18
          is_native: false

      
    - id: "tslax"
      symbol: "TSLAx"
      name: "Tesla xStock"
      items:
        - chain: "SOL"
          address: "XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB"
          decimals: 18
          is_native: false

    - id: "spyx"
      symbol: "SPYx"
      name: "S&P500 ETF xStock"
      items:
        - chain: "SOL"
          address: "XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W"
          decimals: 18
          is_native: false

    - id: "qqqx"
      symbol: "QQQx"
      name: "Nasdaq ETF xStock"
      items:
        - chain: "SOL"
          address: "Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ"
          decimals: 18
          is_native: false

    - id: "nvdax"
      symbol: "NVDAx"
      name: "NVIDIA xStock"
      items:
        - chain: "SOL"
          address: "Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh"
          decimals: 18
          is_native: false

    - id: "mstrx"
      symbol: "MSTRx"
      name: "MicroStrategy xStock"
      items:
        - chain: "SOL"
          address: "XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ"
          decimals: 18
          is_native: false

    - id: "hoodx"
      symbol: "HOODx"
      name: "Robinhood xStock"
      items:
        - chain: "SOL"
          address: "XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg"
          decimals: 18
          is_native: false

    - id: "metax"
      symbol: "METAx"
      name: "Meta xStock"
      items:
        - chain: "SOL"
          address: "Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu"
          decimals: 18
          is_native: false

    - id: "crclx"
      symbol: "CRCLx"
      name: "Circle xStock"
      items:
        - chain: "SOL"
          address: "XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1"
          decimals: 18
          is_native: false

# ##  TODO: BSC, ripple