name: whale-tracker

services:
  postgres:
    image: postgres:16-alpine
    container_name: whale_tracker_db
    environment:
      POSTGRES_USER: tracker_admin
      POSTGRES_PASSWORD: super_secure_password
      POSTGRES_DB: whale_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_server
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password123
      KC_HTTP_PORT: 9090
      KC_HTTPS_PORT: 9443
    ports:
      - "9090:9090"
      - "9443:9443"
    depends_on:
      keycloak-db:
        condition: service_healthy
    volumes:
      - ./deploy/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

  redis:
    image: redis:7-alpine
    container_name: whale_tracker_cache
    ports:
      - "6379:6379"

  keycloak-db:
    image: postgres:16-alpine
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management 
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=supersecretpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mail-relay:
    image: boky/postfix:latest
    container_name: postfix_relay
    restart: unless-stopped
    environment:
      HOSTNAME: mail.example.com
      ALLOWED_SENDER_DOMAINS: test.local
      POSTFIX_smtpd_tls_security_level: none
    ports:
      - "25:25"

volumes:
  pgdata:
  postgres_data:
  rabbitmq_data:

    # gorush:
    #   image: appleboy/gorush
    #   container_name: whale_tracker_push
    #   ports:
    #     - "8088:8088"
    #   environment:
    #     - GORUSH_CORE_PORT=8088
    #     - GORUSH_IOS_ENABLED=true
