
syntax = "proto3";

package price.v1;
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

option go_package = "tracker/gen/price/v1;pricev1";

import "google/api/annotations.proto";

service PriceService {
  rpc ListCoins(ListCoinsRequest) returns (ListCoinsResponse) {
    option (google.api.http) = {
      get: "/v1/coins"
    };
  }
  rpc GetCoin(GetCoinRequest) returns (GetCoinResponse) {
    option (google.api.http) = {
      get: "/v1/coins/{id}"
    };
  }
  rpc SearchCoin(SearchCoinsRequest) returns (SearchCoinsResponse) {
    option (google.api.http) = {
      post: "/v1/coins/search",
      body: "*"
    };
  }

  rpc GetPrices(GetPricesRequest) returns (GetPricesResponse) {
    option (google.api.http) = {
      get: "/v1/prices"
    };
  }
  rpc GetPrice(GetPriceRequest) returns (GetPriceResponse) {
    option (google.api.http) = {
      get: "/v1/prices/{symbol}"
    };
  }
}

message ListCoinsRequest {}

message ListCoinsResponse {
  int32          total = 1;
  repeated Token token = 2;
}

message GetCoinRequest {
  string id = 1;
}
message GetCoinResponse {
  Token token = 1;
}

message GetPricesRequest {
  repeated string symbols = 1;
}

message GetPricesResponse {
  int32          total = 1;
  repeated Price price = 2;
}

message GetPriceRequest {
  string symbol = 1;
}

message GetPriceResponse {
  Price price = 1;
}

message SearchCoinsRequest {
  string text = 1;
}
message SearchCoinsResponse {
  int32          total = 1;
  repeated Token token = 2;
}

message Price {
  string                    symbol                           = 1;
  string                    name                             = 2;
  float                     price_usd                        = 3;
  float                     market_cap                       = 4;
  float                     total_volume                     = 5;
  float                     high_24h                         = 6;
  float                     low_24h                          = 7;
  float                     price_change_24h                 = 8;
  float                     price_change_percentage_24h      = 9;
  float                     market_cap_change_24h            = 10;
  float                     market_cap_change_percentage_24h = 11;
  google.protobuf.Timestamp updated_at                       = 12;
}
message Token {
  string          symbol    = 2;
  string          name      = 3;
  repeated string chains    = 4;
  repeated string addrs     = 5;
  bool            is_native = 6;
  string          image_url = 7;
}