
syntax = "proto3";

package wallet.v1;
import "google/protobuf/empty.proto";

option go_package = "github.com/yourusername/yourrepo/gen/go/wallet/v1;walletv1";

import "google/api/annotations.proto";

service WalletService {
  rpc GetWallets(GetWalletsReq) returns (GetWalletsResp) {
    option (google.api.http) = {
      get: "/v1/wallets"
    };
  }
  rpc GetWallet(GetWalletReq) returns (GetWalletResp) {
    option (google.api.http) = {
      get: "/v1/wallets/{id}"
    };
  }
  rpc EditWallet(EditWalletReq) returns (EditWalletResp) {
    option (google.api.http) = {
      patch: "/v1/wallets/{id}"
      body : "*"
    };
  }
  rpc DeleteWallet(DeleteWalletReq) returns (DeleteWalletResp) {
    option (google.api.http) = {
      delete: "/v1/wallets/{id}"
    };
  }
  rpc AddWallet(AddWalletReq) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/v1/wallets"
      body: "*"
    };
  }
}

message GetWalletsReq {}

message GetWalletsResp {
  int32           total  = 1;
  repeated Wallet wallet = 2;
}

message GetWalletReq {
  string id = 1;
}

message GetWalletResp {
  string id                 = 1;
  string address            = 2;
  string chain              = 3;
  string token_symbol       = 4;
  string label              = 5;
  float  balance_crypto     = 6;
  float  balance_usd        = 7;
  float  change_24h_percent = 8;
  bool   has_error          = 9;
  string error_msg          = 10;
}

message EditWalletReq {
  string id    = 1;
  string label = 2;
}

message EditWalletResp {
  Wallet wallet = 1;
}

message DeleteWalletReq {
  string id = 1;
}

message DeleteWalletResp {
  string deleted_id = 1;
}

message AddWalletReq {
  string address            = 2;
  string chain              = 3;
  string token_symbol       = 4;
  string label              = 5;
  float  balance_crypto     = 6;
  float  balance_usd        = 7;
  float  change_24h_percent = 8;
  bool   has_error          = 9;
  string error_msg          = 10;
}

message Wallet {
  string id                 = 1;
  string address            = 2;
  string chain              = 3;
  string token_symbol       = 4;
  string label              = 5;
  float  balance_crypto     = 6;
  float  balance_usd        = 7;
  float  change_24h_percent = 8;
  bool   has_error          = 9;
  string error_msg          = 10;
}